RabbitMQSender/Models/ErrorViewModel.cs
using System;

namespace RabbitMQSender.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RabbitMQSender/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RabbitMQSender.Models
{
    public class User
    {
        [Required]
        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [Required]
        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [Required]
        [DisplayName("Email Address")]
        [DataType(DataType.EmailAddress)]
        public string EmailAddress { get; set; }
    }
}

RabbitMQSender/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RabbitMQSender.Models;

namespace RabbitMQSender.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RabbitMQSender/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using RabbitMQ.Client;
using RabbitMQSender.Models;

namespace RabbitMQSender.Controllers
{
    [AllowAnonymous]
    public class UserController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly ILogger<UserController> _logger;

        public UserController(IConfiguration configuration, ILogger<UserController> logger) 
        {
            _configuration = configuration;
            _logger = logger;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SendUserQueue()
        {
            User viewmodel = new User();

            return View(viewmodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SendUserQueue(User viewmodel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string senderUniqueId = "userInsertQueue";
                    var factory = new ConnectionFactory()
                    {
                        HostName = _configuration.GetValue<string>("RabbitMQConfig:HostName"),
                        Port = _configuration.GetValue<int>("RabbitMQConfig:Port"),
                        UserName = _configuration.GetValue<string>("RabbitMQConfig:UserName"),
                        Password = _configuration.GetValue<string>("RabbitMQConfig:Password"),
                        VirtualHost = _configuration.GetValue<string>("RabbitMQConfig:VirtualHost"),
                    };

                    _logger.LogInformation("Creating RabbitMQ Connection");

                    using (var connection = factory.CreateConnection())
                    using (var channel = connection.CreateModel())
                    {
                        channel.QueueDeclare(queue: "userInsertQueue", durable: false, exclusive: false, autoDelete: false, arguments: null);

                        string message = JsonConvert.SerializeObject(viewmodel);

                        var body = Encoding.UTF8.GetBytes(message);

                        IBasicProperties properties = channel.CreateBasicProperties();
                        properties.Persistent = true;
                        properties.DeliveryMode = 2;
                        properties.Headers = new Dictionary<string, object>();
                        properties.Headers.Add("senderUniqueId", senderUniqueId);

                        channel.BasicPublish(exchange: "",
                                             routingKey: "userInsertQueue",
                                             basicProperties: properties,
                                             body: body);
                    }

                    return View(viewmodel);
                }
                catch(Exception ex)
                {
                    return View(ex);
                }
            }

            return View(viewmodel);
        }
    }
}

RabbitMQSender/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>User Page: <a asp-controller="User" asp-action="SendUserQueue">Send User Message to the Console App</a>.</p>
    </div>

RabbitMQSender/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RabbitMQSender</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RabbitMQSender</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - RabbitMQSender - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

RabbitMQSender/Views/User/Index.cshtml
@{
    ViewData["Title"] = "User List";
}
<h1>Welcome to User Page</h1>
@Html.ActionLink("Click here to redirect to User Queue page", "SendUserQueue", "User")

RabbitMQSender/Views/User/SendUserQueue.cshtml
@model User

@{
    ViewData["Title"] = "Send User Queue";
}

<div class="container">
    <div class="user-form">
        <form asp-controller="User" asp-action="SendUserQueue" method="post">
            @Html.ValidationSummary(true)
            <h4>Send User</h4>
            <hr />
            <div class="form-group">
                @Html.LabelFor(m => m.FirstName):
                @Html.TextBoxFor(m => m.FirstName, null, new { @class = "form-control input-lg", placeholder = "First Name" })
                @Html.ValidationMessageFor(m => m.FirstName)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.LastName):
                @Html.TextBoxFor(m => m.LastName, null, new { @class = "form-control input-lg", placeholder = "Last Name" })
                @Html.ValidationMessageFor(m => m.LastName)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.EmailAddress):
                @Html.TextBoxFor(m => m.EmailAddress, null, new { @class = "form-control input-lg", placeholder = "Email Address" })
                @Html.ValidationMessageFor(m => m.EmailAddress)
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success btn-lg btn-block signup-btn" name="button" value="login">Send</button>
            </div>
        </form>
        <a asp-controller="Home" asp-action="Index">Return to Homepage</a>
    </div>
</div>

<style>
    .field-validation-error {
        color: #dc3545!important;
    }
</style>